model_param:
  # ssl model can be chosen:
      # hubert_base hubert_large 
      # wav2vec2_base_960 wav2vec2_large_lv60_cv_swbd_fsh 
      # wavlm_base wavlm_large
      # xls_r_300m
  ssl_model_type: "wav2vec2_base_960"
  hdim: 128
  # f0 related
  use_f0: false
  use_f0_var: false
  # judge related
  use_judge_id : false
  use_lstm : false
  judge_num: 50
  # projection layer
  activate_func: "relu"
  output_type: "scalar"
  mos_clip: true
  # loss related
  loss_type: "L2"
  use_margin: true
  margin: 0.1
  use_frame_level: false
  alpha_judge: 0.8
  alpha_frame: 0.5

